version: "3"
services:
  database1:
    image: mysql
    container_name: mysql1
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - ../sql:/docker-entrypoint-initdb.d/:ro
    cap_add: # this prevents "mbind: Operation not permitted" when creating the schema
      - SYS_NICE

  database2:
    image: mysql
    container_name: mysql2
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    volumes:
      - ../sql:/docker-entrypoint-initdb.d/:ro
    cap_add: # this prevents "mbind: Operation not permitted" when creating the schema
      - SYS_NICE