version: "3"
services:
  database:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    volumes:
      - ./src/sql:/docker-entrypoint-initdb.d/:ro
