java -jar target/demo-0.0.1-SNAPSHOT.jar > log1.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log2.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log3.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log4.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log5.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log6.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log7.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log8.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log9.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log10.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log11.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log12.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log13.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log14.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log15.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log16.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log17.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log18.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log19.txt &
java -jar target/demo-0.0.1-SNAPSHOT.jar > log20.txt &
